### ISSUE TITLE
Err, how do I register an app?

### ISSUE THREAD

**Issue by JohnSmall** [Sage/sageone_api_ruby_sample#12]
I've tried registering an app online, but the server checks my callback, which obviously doesn't work unless I've got the client_id, client_secret and signing_secret which I get after I've registered an app.

So I can't register an app, unless I have the information I get after registering an app.

Here's the tail of my production.log
`
I, [2017-03-03T07:45:13.433023 #17273]  INFO -- : Started GET "/auth/callback" for 213.205.194.174 at 2017-03-03 07:45:13 +0000
I, [2017-03-03T07:45:13.454765 #17273]  INFO -- : Processing by SageOneController#exchange_code_for_token as HTML
I, [2017-03-03T07:45:13.540115 #17273]  INFO -- : Completed 500 Internal Server Error in 85ms (ActiveRecord: 0.0ms)
F, [2017-03-03T07:45:13.540962 #17273] FATAL -- : 
RestClient::BadRequest (400 Bad Request):
  app/controllers/sage_one_controller.rb:92:in `get_token'
  app/controllers/sage_one_controller.rb:18:in `exchange_code_for_token'
`

**Comment by cpetschnig** [comment]
Hi John,

did you go through the steps at https://developers.sageone.com/ ? Step 4 has the link to the [app registration](https://developer.sageone.com/applications/new).

Does this help?
